main: com.winthier.kit.KitPlugin
name: Kit

version: 0.1
api-version: '1.20'

description: Give people kits
author: StarTux

depend: [Core, SQL, Mytems, MemberList, Title, Inventory, Fam]
softdepend: []

commands:

  kit:
    description: Select a kit
    permission: kit.kit
    usage: /kit

  kitadmin:
    aliases: [kita, kite]
    permission: kit.admin
    description: Admin interface
    usage: /kitadmin

permissions:

  kit.kit:
    default: op
    description: Use the /kit command

  kit.admin:
    default: op
    description: Use admin commands