main: com.winthier.kit.KitPlugin
name: Kit
description: Give people kits
author: StarTux
version: 0.1
api-version: 1.13
depend: [GenericEvents]
commands:
  kit:
    description: Select a kit
    permission: kit.kit
    usage: |-
      /kit - List kits
      /kit <kit> - Claim kit
  kitadmin:
    permission: kit.admin
    description: Admin interface
    usage: |-
      /kitadmin reload - Reload
      /kitadmin give <player> <kit> - Give to player
      /kitadmin cooldowns - List kit cooldowns
      /kitadmin cooldowns <kit> - List kit cooldowns
      /kitadmin player <name> - List player cooldowns
      /kitadmin set <kit> <player> [seconds] - (Re)set cooldown
permissions:
  kit.kit:
    default: op
    description: Use the /kit command
  kit.admin:
    default: op
    description: Use admin commands